### ISSUE TITLE
.

### ISSUE THREAD

**Issue by thefangbear** [BKmaster2580/LScrawlerPython#2]
Not including those modules is like eating something really unpleasant and swallowing them down your esophagus. Never ever don't include a module.

**Comment by frjalex** [comment]
Also your script will never run on most systems. Stupid module errors always pop up.

I created a pull request for this, ready to merge :) :+1: https://github.com/BKmaster2580/LScrawlerPython/pull/3

**Comment by frjalex** [comment]
See https://github.com/BKmaster2580/LScrawlerPython/pull/3
